COMMAND=virsh
SUBCOMMANDS=(
        help
        attach-device
        attach-disk
        attach-interface
        autostart
        capabilities
        cd
        connect
        console
        cpu-baseline
        cpu-compare
        create
        start
        destroy
        detach-device
        detach-disk
        detach-interface
        define
        domid
        domuuid
        dominfo
        domjobinfo
        domjobabort
        domname
        domstate
        domblkstat
        domifstat
        dommemstat
        domblkinfo
        domxml-from-native
        domxml-to-native
        dumpxml
        edit
        find-storage-pool-sources
        find-storage-pool-sources-as
        freecell
        hostname
        list
        migrate
        migrate-setmaxdowntime
        net-autostart
        net-create
        net-define
        net-destroy
        net-dumpxml
        net-edit
        net-list
        net-name
        net-start
        net-undefine
        net-uuid
        iface-list
        iface-name
        iface-mac
        iface-dumpxml
        iface-define
        iface-undefine
        iface-edit
        iface-start
        iface-destroy
        managedsave
        managedsave-remove
        nodeinfo
        nodedev-list
        nodedev-dumpxml
        nodedev-dettach
        nodedev-reattach
        nodedev-reset
        nodedev-create
        nodedev-destroy
        nwfilter-define
        nwfilter-undefine
        nwfilter-dumpxml
        nwfilter-list
        nwfilter-edit
        pool-autostart
        pool-build
        pool-create
        pool-create-as
        pool-define
        pool-define-as
        pool-destroy
        pool-delete
        pool-dumpxml
        pool-edit
        pool-info
        pool-list
        pool-name
        pool-refresh
        pool-start
        pool-undefine
        pool-uuid
        secret-define
        secret-dumpxml
        secret-set-value
        secret-get-value
        secret-undefine
        secret-list
        pwd
        quit
        exit
        reboot
        restore
        resume
        save
        schedinfo
        dump
        shutdown
        setmem
        setmaxmem
        setvcpus
        suspend
        ttyconsole
        undefine
        update-device
        uri
        vol-create
        vol-create-from
        vol-create-as
        vol-clone
        vol-delete
        vol-wipe
        vol-dumpxml
        vol-info
        vol-list
        vol-pool
        vol-path
        vol-name
        vol-key
        vcpuinfo
        vcpupin
        version
        vncdisplay
        snapshot-create
        snapshot-current
        snapshot-delete
        snapshot-dumpxml
        snapshot-list
        snapshot-revert )

        compctl -k "($SUBCOMMANDS)" $COMMAND
